# Set general paths
set(ROOT_SRC_DIR             ${CMAKE_SOURCE_DIR}/../../src)
set(THIRD_PARTY_DIR          ${ROOT_SRC_DIR}/Third-Party)
set(BSP_DIR                  ${ROOT_SRC_DIR}/Bsp)
set(OS_DIR                   ${ROOT_SRC_DIR}/Os)
set(PROJECT_DIR              ${ROOT_SRC_DIR}/Project/${PROJECT})
set(TOOLS_DIR                ${CMAKE_SOURCE_DIR}/../../tools)
set(BUILD_DIR                ${CMAKE_SOURCE_DIR}/../../build)
set(BIN_DIR                  ${BUILD_DIR}/target/bin)
set(DEPLOY_DIR               ${BIN_DIR}/${PROJECT})
set(UTEST_DIR                ${CMAKE_SOURCE_DIR}/../../utest)
