# Set general paths
set(ROOT_SRC_DIR             ${CMAKE_SOURCE_DIR}/../src)
set(PROJECT_DIR              ${ROOT_SRC_DIR}/Project/${PROJECT})
set(CMSIS_DIR                ${ROOT_SRC_DIR}/CMSIS)
set(DRIVER_DIR               ${ROOT_SRC_DIR}/Drivers)
set(OS_DIR                   ${ROOT_SRC_DIR}/Os)
set(FREERTOS_DIR             ${OS_DIR}/FreeRTOS)
set(OSEK _DIR                ${OS_DIR}/Osek)
set(IOTOS_DIR                ${OS_DIR}/IoTOS)
set(BSW_DIR                  ${PROJECT_DIR}/Bsw)
set(APP_DIR                  ${PROJECT_DIR}/App)
set(CONFIG_DIR               ${PROJECT_DIR}/Cfg)
set(DEBUG_DIR                ${PROJECT_DIR}/Debug)
set(STARTUP_DIR              ${PROJECT_DIR}/Startup)
set(TOOLS_DIR                ${CMAKE_SOURCE_DIR}/../tools)
set(BUILD_DIR                ${CMAKE_SOURCE_DIR}/../build)
set(BIN_DIR                  ${BUILD_DIR}/bin)
set(DEPLOY_DIR               ${BIN_DIR}/${PROJECT})

